### ISSUE TITLE
409 Conflict for Import Keys - If keys already exist for app

### ISSUE THREAD

**Issue by aakashsharmaquilter** [apigee/apigee-config-maven-plugin#123]
For Apps with import keys if we run update operation again it fails with 409 Conflict. As new apps are added on platform we need some way to import keys through ci/cd. When we add new keys it imports them, but just errors out for old apps wherever key matches. It should  work similar to KVM that if exist it overwrites existing key and for new key add them

[ERROR] Apigee call failed 409 Conflict
{
  "code" : "keymanagement.service.ConsumerKeyAlreadyExists",
  "message" : "ConsumerKey already exists",
  "contexts" : [ ]
}

Ref: https://github.com/apigee/apigee-config-maven-plugin/issues/17

**Comment by ssvaidyanathan** [comment]
@aakashsharmaquilter - why are you running importKeys again? Shouldn't it be a single time operation when you really need it? importKeys is meant for a certain functionality. You are expecting that to work like update function on the app which isn't right. I would suggest you update your pipeline to call importKeys separately so that its not run every time.

**Comment by aakashsharmaquilter** [comment]
hi @ssvaidyanathan how should then one import new keys for apps. Even after separating out deployment and consumption configurations. If we run create/update/importkey on consumption profile it runs in to 409 conflict. Even if we run importkey goal separately it will  still error out 409 conflict for existing app keys. Please suggest.

**Comment by ssvaidyanathan** [comment]
Not sure I understand - can you explain your process of how you onboard new apps and their keys?

**Comment by aakashsharmaquilter** [comment]
we are importing keys from azure AD. So app gets created first on Azure AD and we have to import the key in to Apigee app. We are using maven replacer with the command in our CI pipeline.  - mvn install -P deploy -Dusername=xx@xx.com -Dpassword=x -Dorg=org1 -Dapigee.config.dir=./resources/edge -Dapigee.config.options=update -Denv=test -DconsumerKey=abc -DconsumerSecret=def -Dapigee.app.ignoreAPIProducts=true

Is that the right way to go about import keys.

**Comment by ssvaidyanathan** [comment]
I would suggest using `apigee-config:importKeys` for that. The sample for that is available [here](https://github.com/apigee/apigee-config-maven-plugin/blob/master/samples/EdgeConfig/resources/edge/org/importKeys.json). With that you can import the app and the creds. Once done, make sure that payload is available in the developerApps.json going forward so that you dont need to keep importing the same keys and then you can just use the `apigee.app.ignoreAPIProducts` option to avoid the plugin from generating new credentials.

**Comment by aakashsharmaquilter** [comment]
With developer apps we will not be able to store credentials in source code repo due to security. So what i understand is that we update importkeys.json on need basis when we have to import keys for app (This could be through replacer instead of actual keys in github) and then run apigee-config:importKeys. Once success then we remove the key from importkeys.json to avoid conflict next time. And we maintain keys-apps mapping outside of source code repo in case we need to reconstruct environment using infra as code practice. Please confirm.

**Comment by ssvaidyanathan** [comment]
You could... or....
When you want to import, just have your importKeys.json ready with the necessary information. Dont commit that file.. Run the apigee-config:importKeys to import that app to Apigee. Once thats done. You can then add that app details (without the credentials) to the developerApps.json and commit that file so that going forward if you want to update the app details, you can manage that through the source code and using apigee-config:apps 
Does that make sense?

**Comment by aakashsharmaquilter** [comment]
In that case Running the apigee-config:importKeys to import keys is that separated out from CI/CD. E.g An admin/developer executing from local system.
One may not want to pass credentials directly but integrate with vault or secret variables and keep an audit/track on same. thanks!

**Comment by ssvaidyanathan** [comment]
Yes - importing is a one-off process and could be done outside of your pipeline. Usually repeatable process is what is in a pipeline. I dont see importing as a "repeatable" process.

If this has answered your question. Can we close this comment?

**Comment by aakashsharmaquilter** [comment]
thanks @ssvaidyanathan  please close then.

**Comment by ssvaidyanathan** [comment]
Thanks @aakashsharmaquilter 
You should be able to close it as well. Closing on your behalf

Appreciate the collaboration

**Comment by dineshpalanivel** [comment]
@ssvaidyanathan Wondering if its still worthwhile to explore honoring the JVM arguments like "update, sync", etc. for **importKeys** goal. I was waiting for a patch and didn't realize that the issue got closed.

If it is OK, I will be happy to submit a PR. 

Thoughts?

**Comment by ssvaidyanathan** [comment]
But why ? Why would you want update/sync on importKeys? Once the app is imported, you can always use the app goal to update the app attributes.

**Comment by dineshpalanivel** [comment]
Imagine if you have two different API Gateways and a requirement to sync them up constantly in terms of api keys and secrets.. It would rather be easier for us to sync or update rather than checking every key on a case by case basis.

**Comment by dineshpalanivel** [comment]
Also, looking at the usability, the current **importKeys** goal doesn't give the flexibility like every other goals that are currently supported by the plugin. I'm not sure how many customers will use it effectively to address a spectrum of needs and us being one among them who is unable to use it in the current state.

**Comment by ssvaidyanathan** [comment]
> Imagine if you have two different API Gateways and a requirement to sync them up constantly in terms of api keys and secrets.. It would rather be easier for us to sync or update rather than checking every key on a case by case basis.

Why would I need to sync the same set of apps frequently? What changes in the app that requires you to keep "importing" rather than updating.. If you still want to update, why not use "apigee-config:app -Dapigee.config.options=delete" and then "apigee-config:importkeys" ??

I do not see this as a common ask.

**Comment by ssvaidyanathan** [comment]
> Also, looking at the usability, the current **importKeys** goal doesn't give the flexibility like every other goals that are currently supported by the plugin. I'm not sure how many customers will use it effectively to address a spectrum of needs and us being one among them who is unable to use it in the current state.

Thats true - it is not expected that every goal in this plugin should have that option. For example exportAppKeys doesn't have those options either. There are some goals that does not support "update".

**Comment by dineshpalanivel** [comment]
> > Imagine if you have two different API Gateways and a requirement to sync them up constantly in terms of api keys and secrets.. It would rather be easier for us to sync or update rather than checking every key on a case by case basis.
> 
> Why would I need to sync the same set of apps frequently? What changes in the app that requires you to keep "importing" rather than updating.. If you still want to update, why not use "apigee-config:app -Dapigee.config.options=delete" and then "apigee-config:importkeys" ??
> 
> I do not see this as a common ask.

No issues. I think we don't have a way to utilize this plugin and continue using what we have built internally.  Thanks.
