### ISSUE TITLE
API Products update

### ISSUE THREAD

**Issue by EmmanuelGillet** [apigee/apigee-config-maven-plugin#133]
Hello 

this issue is related to #111 

We have the monetization feature and we have the same error described in the issue 

When using the product, if we assign the apigee.config.options=update, we have the same error, but we can not have the possiblity to change the name : we want to really update the API Products and not create a new one.

It should just change the attributes of the API Products (scope, access, etc...) 

We can see that the command is a POST (create) rather than a PUT (update) though the apigee.config.options is correctly set

The version I used is for apigeeEdge : 1.4.5

```bash
POST  https://api.enterprise.apigee.com/v1/organizations/xxx-noprod/apiproducts
[ERROR] Apigee call failed 500 Server Error
{
  "code" : "mint.unhandledException",
  "message" : "Unanticipated exception. Please contact your Support administrator with code : dd469665-9846-4677-a169-def30d49f68b",
  "contexts" : [ ],
  "cause" : {
    "message" : "The transaction has been rolled back.  See the nested exceptions for details on the errors that occurred.",
    "contexts" : [ ],
    "cause" : {
      "message" : "ERROR: duplicate key value violates unique constraint \"product_pkey\"\...
      }
    }
  }
}
```

**Comment by EmmanuelGillet** [comment]
I have been looking for the different change, and I found out what was incorrect : during the first and the second run, the name of the product was transformed from "priv-name" to "priv-Name". I assume the case was not handled correctly in the tool
I removed all my api products and did the same process but keeping the case, and I could see the PUT command used, the name was found during the check.
but in the Database, the case was a problem.

**Comment by ssvaidyanathan** [comment]
@EmmanuelGillet - not sure I am following the explanation. Are you saying the plugin is updating the name? If you are, thats not the case. The plugin takes the payload as is and calls the Management API. I know for a fact that when Monetization is enabled, the Product name becomes case sensitive. Can you check if the data being stored is being altered? Can you use the API to get the Product info and see? From the details you provided, either the payload is being changed by something in your workflow or there is a bug in the product thats causing this. For the former, can you please check the pipeline and the overall logs? If its the latter, you will need to open a Support ticket and have them check it. I would also recommend you to try creating the product, getting the product info and updating it all via APIs to see if its working as expected. Because this is exactly what the plugin does too
