### ISSUE TITLE
This API product is created in legacy format so API resources and API paths shown below, may only be present in this case.

### ISSUE THREAD

**Issue by xjjh1** [apigee/apigee-config-maven-plugin#158]
Tested in Hybrid 1.6 and 1.7, apigee-config-maven-plugin: 2.4.0

Below warning is shown on the API product when an API product is created using this plugin

`This API product is created in legacy format so API resources and API paths shown below, may only be present in this case.`

API products are getting created but the UI is showing in old/odd format. The operations section in the API product is different when it is created with this maven plugin compared to the API products created in GUI. 

Please refer to the images attached below, you can notice the difference in operations and other sections. 

**Without Warning - api product created via UI:**

![apiproduct-withoutwarning](https://user-images.githubusercontent.com/91582840/184183146-9f693e81-783d-40ad-97f9-673c466db881.jpg)

**With Warning - using this maven plugin:**

![apiproduct-withwarning](https://user-images.githubusercontent.com/91582840/184183181-7e23ccf6-1e32-4e58-b29d-c9ec8ef72554.jpg)

FYI - @msadasivam @ssvaidyanathan

**Comment by ssvaidyanathan** [comment]
Hi @xjjh1 - This is working as expected. 
This is because of the API Product payload you are passing. With the introduction of Operation Groups and GraphQL, the payload for creating the API Products are changed too. For backward compatibility, the previous payload still works and hence you see the legacy API Product warning. For the new API Product, you can refer this [sample](https://github.com/apigee/apigee-config-maven-plugin/blob/hybrid/samples/EdgeConfig/resources/edge/org/apiProducts.json) where I have both examples. Try it out and let me know if you have any other issues. If it works, then please update here and close the issue

**Comment by xjjh1** [comment]
Hi @ssvaidyanathan 

Thanks for the details. I overlooked it. 

I have tested it and it works.
