### ISSUE TITLE
Please add support for our own API keys

### ISSUE THREAD

**Issue by zabela** [apigee/apigee-config-maven-plugin#70]
Currently there is no clean solution to update the consumer_id with the maven plugin.

One needs to develop their own API calls to do so like [this example](https://community.apigee.com/questions/53627/how-can-i-update-consumer-secret-from-an-api-proxy.html), that goes into how to create a creds-set and then delete the old one. 

Thus, would be great to add a way to handle that from the maven plugin side and that is why I am creating this issue.

**Comment by ssvaidyanathan** [comment]
@zabela - thanks for opening this issue. how often do you see this needed ? How do you plan to use this plugin for this purpose ?

**Comment by zabela** [comment]
Sure @ssvaidyanathan. Well, I think anyone that uses this plugin for development might have faced this at some point when maintaining the developer apps data from your codebase. I.e. deploying the developer apps from source control rather than updating them via the apigee console so that we can track the changes and also, as a DR strategy to be able to recreate the same apikeys in case of app/apikey deletion.

**Comment by gsjurseth** [comment]
I now need this for a specific use case. I don't think it's something that will come up too often, but when it does it would be nice to have something supported in this plugin. I'm thinking an optional parameter in the json for any individual app to override the generated key and secret and replace with whatever is in the json.

Looking at source I'm thinking I could probably just do this inside of AppMojo, but maybe you can tell me otherwise.

**Comment by ssvaidyanathan** [comment]
Released in v1.4.1
